export type Lang = 'zh' | 'en'

export type BilingualText = {
  zh: string
  en: string
}

export type SkillCategory = '生活' | '家庭' | '安全' | '健康' | '学习' | '机构'

export type SkillItem = {
  id: number
  name: BilingualText
  description: BilingualText
  category: SkillCategory
  provider: string
  price: BilingualText
  featured?: boolean
}

export const media = {
  homeVideo: 'https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260711_090308_1dd0cea7-f9ba-4db4-8147-c7d746061c9e.mp4',
  memoraVideo: 'https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260702_102608_5fa1187d-9ac6-44fb-82ab-54376200abc0.mp4',
  skillVideo: 'https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260625_174131_395bc785-bb21-4e65-abf6-27c56f0764b6.mp4',
  silverHero: '/images/silveros-android-ai-native-hero-v2.webp',
  seniorPhone: 'https://images.unsplash.com/photo-1776176065418-8d33aeca47e4?auto=format&fit=crop&fm=jpg&q=82&w=1800',
  communitySquare: 'https://images.unsplash.com/photo-1755053757569-1559444c1918?auto=format&fit=crop&fm=jpg&q=82&w=1800',
  knittingPortrait: 'https://images.unsplash.com/photo-1774094135149-bbeeb1767bfa?auto=format&fit=crop&fm=jpg&q=82&w=1600',
  workshop: 'https://images.unsplash.com/photo-1763994684995-7ae6c49b7212?auto=format&fit=crop&fm=jpg&q=82&w=1800',
  threeGenerations: 'https://images.unsplash.com/photo-1742750278243-6596976af769?auto=format&fit=crop&fm=jpg&q=82&w=1800',
  conversation: 'https://images.unsplash.com/photo-1781246013729-58af33b0aed9?auto=format&fit=crop&fm=jpg&q=82&w=1800',
} as const

export const skillCategories: Array<{ key: '全部' | SkillCategory; zh: string; en: string }> = [
  { key: '全部', zh: '全部', en: 'All' },
  { key: '生活', zh: '日常生活', en: 'Daily life' },
  { key: '家庭', zh: '家庭沟通', en: 'Family' },
  { key: '安全', zh: '安全守护', en: 'Safety' },
  { key: '健康', zh: '健康支持', en: 'Health' },
  { key: '学习', zh: '学习娱乐', en: 'Learning' },
  { key: '机构', zh: '机构服务', en: 'Providers' },
]

export const skills: SkillItem[] = [
  {
    id: 1,
    name: { zh: '反诈消息检查', en: 'Scam Message Check' },
    description: { zh: '识别可疑链接、诱导话术与异常转账请求。', en: 'Flags suspicious links, pressure tactics, and unusual payment requests.' },
    category: '安全',
    provider: 'Deerlight Safety',
    price: { zh: '免费', en: 'Free' },
    featured: true,
  },
  {
    id: 2,
    name: { zh: '家人消息助手', en: 'Family Message Helper' },
    description: { zh: '把语音、长消息和家庭群通知整理成易读摘要。', en: 'Turns voice notes and busy family chats into clear summaries.' },
    category: '家庭',
    provider: 'Kindred AI',
    price: { zh: '免费', en: 'Free' },
    featured: true,
  },
  {
    id: 3,
    name: { zh: '就医准备清单', en: 'Visit Prep' },
    description: { zh: '整理症状、用药、既往问题与要问医生的问题。', en: 'Organizes symptoms, medication, history, and questions before a visit.' },
    category: '健康',
    provider: 'CareNote',
    price: { zh: '¥8 / 月', en: '¥8 / mo' },
    featured: true,
  },
  {
    id: 4,
    name: { zh: '数字生活教练', en: 'Digital Life Coach' },
    description: { zh: '一步一步教会拍照、打车、视频通话与移动支付。', en: 'Step-by-step help for photos, rides, video calls, and payments.' },
    category: '学习',
    provider: 'Deerlight Learn',
    price: { zh: '免费', en: 'Free' },
  },
  {
    id: 5,
    name: { zh: '用药节奏', en: 'Medication Rhythm' },
    description: { zh: '用温和提醒、确认与家人协作维持用药节奏。', en: 'Gentle reminders and family-aware confirmations for medication routines.' },
    category: '健康',
    provider: 'Rhythm Care',
    price: { zh: '¥12 / 月', en: '¥12 / mo' },
  },
  {
    id: 6,
    name: { zh: '出行规划助手', en: 'Easy Trip Planner' },
    description: { zh: '优先无障碍、少换乘和熟悉路线，生成清晰行程。', en: 'Plans accessible, low-transfer, familiar routes with clear instructions.' },
    category: '生活',
    provider: 'Wayhome',
    price: { zh: '免费', en: 'Free' },
  },
  {
    id: 7,
    name: { zh: '家庭纪念日', en: 'Family Dates' },
    description: { zh: '管理生日、纪念日与家庭传统，并准备贴心提醒。', en: 'Keeps birthdays, anniversaries, and family traditions thoughtfully organized.' },
    category: '家庭',
    provider: 'Memora',
    price: { zh: '¥18 一次性', en: '¥18 once' },
  },
  {
    id: 8,
    name: { zh: '照片回忆讲述', en: 'Photo Memory Story' },
    description: { zh: '围绕一张旧照片展开引导式回忆与家人共写。', en: 'Guides a memory conversation around an old photo with family input.' },
    category: '家庭',
    provider: 'Memora',
    price: { zh: '¥18 / 月', en: '¥18 / mo' },
    featured: true,
  },
  {
    id: 9,
    name: { zh: '购物清单搭子', en: 'Shopping Companion' },
    description: { zh: '通过语音维护清单，并按商店动线自动归类。', en: 'Maintains voice-first lists and groups items by store aisle.' },
    category: '生活',
    provider: 'Goodday Studio',
    price: { zh: '免费', en: 'Free' },
  },
  {
    id: 10,
    name: { zh: '可信联系人', en: 'Trusted Contacts' },
    description: { zh: '在重要操作前快速找到并联系正确的家人或服务方。', en: 'Finds the right trusted person before important digital actions.' },
    category: '安全',
    provider: 'Deerlight Safety',
    price: { zh: '免费', en: 'Free' },
  },
  {
    id: 11,
    name: { zh: '合同看明白', en: 'Plain-language Contracts' },
    description: { zh: '把服务条款、账单和合同解释成清晰的普通话。', en: 'Explains bills, contracts, and service terms in plain language.' },
    category: '安全',
    provider: 'Plainly',
    price: { zh: '¥6 / 次', en: '¥6 / use' },
  },
  {
    id: 12,
    name: { zh: '每日轻运动', en: 'Gentle Daily Movement' },
    description: { zh: '根据身体状态与家中空间生成短时轻运动建议。', en: 'Creates short, gentle movement sessions for the user and their space.' },
    category: '健康',
    provider: 'Mellow Motion',
    price: { zh: '¥10 / 月', en: '¥10 / mo' },
  },
  {
    id: 13,
    name: { zh: '兴趣学习伙伴', en: 'Interest Learning Buddy' },
    description: { zh: '围绕戏曲、摄影、园艺等兴趣安排低压力学习。', en: 'Plans low-pressure learning around music, photography, gardening, and more.' },
    category: '学习',
    provider: 'Evergreen',
    price: { zh: '¥12 / 月', en: '¥12 / mo' },
  },
  {
    id: 14,
    name: { zh: '方言家书', en: 'Dialect Family Letters' },
    description: { zh: '保留熟悉的表达方式，把口述整理成可分享的家书。', en: 'Keeps familiar expressions while shaping spoken memories into letters.' },
    category: '家庭',
    provider: 'Home Voice',
    price: { zh: '¥3 / 封', en: '¥3 / letter' },
  },
  {
    id: 15,
    name: { zh: '入住陪伴员', en: 'Move-in Companion' },
    description: { zh: '为新入住长者解释环境、流程与每日安排。', en: 'Explains spaces, routines, and daily plans to new residents.' },
    category: '机构',
    provider: 'Harbor Living',
    price: { zh: '机构订阅', en: 'Provider plan' },
  },
  {
    id: 16,
    name: { zh: '服务记录 Copilot', en: 'Service Note Copilot' },
    description: { zh: '将一线员工口述转为结构化、可追踪的服务记录。', en: 'Turns frontline voice notes into structured, traceable service records.' },
    category: '机构',
    provider: 'CareOps',
    price: { zh: '机构订阅', en: 'Provider plan' },
  },
  {
    id: 17,
    name: { zh: '活动灵感库', en: 'Activity Idea Bank' },
    description: { zh: '根据参与者能力、兴趣与场地生成小组活动方案。', en: 'Creates group activities around ability, interests, and available space.' },
    category: '机构',
    provider: 'Common Room',
    price: { zh: '¥99 / 月', en: '¥99 / mo' },
  },
  {
    id: 18,
    name: { zh: '智能设备引导', en: 'Device Walkthrough' },
    description: { zh: '把复杂设置拆成一句一屏、随时可回退的操作步骤。', en: 'Breaks complicated settings into one clear, reversible step per screen.' },
    category: '学习',
    provider: 'Deerlight Learn',
    price: { zh: '免费', en: 'Free' },
  },
  {
    id: 19,
    name: { zh: '通知摘要', en: 'Notification Digest' },
    description: { zh: '把一天的重要通知合并成清楚、可追问的摘要。', en: 'Combines important notifications into one clear, askable digest.' },
    category: '生活',
    provider: 'Deerlight Labs',
    price: { zh: '免费', en: 'Free' },
    featured: true,
  },
  {
    id: 20,
    name: { zh: '语音日历', en: 'Voice Calendar' },
    description: { zh: '用自然语言新增日程、调整时间并提醒相关家人。', en: 'Adds and changes plans by voice, with optional family reminders.' },
    category: '生活',
    provider: 'Dayline',
    price: { zh: '免费', en: 'Free' },
  },
  {
    id: 21,
    name: { zh: '账单看明白', en: 'Bill Explainer' },
    description: { zh: '标出费用、到期日、自动续费与需要确认的异常项目。', en: 'Highlights charges, due dates, renewals, and items worth checking.' },
    category: '安全',
    provider: 'Plainly',
    price: { zh: '¥6 / 次', en: '¥6 / use' },
  },
  {
    id: 22,
    name: { zh: '陌生来电提醒', en: 'Unknown Caller Check' },
    description: { zh: '通话前展示风险提示，通话后整理承诺与待确认事项。', en: 'Shows risk context before a call and summarizes claims afterward.' },
    category: '安全',
    provider: 'Deerlight Safety',
    price: { zh: '免费', en: 'Free' },
    featured: true,
  },
  {
    id: 23,
    name: { zh: '支付二次确认', en: 'Payment Double Check' },
    description: { zh: '转账或付款前核对对象、金额、原因和常见风险。', en: 'Rechecks recipient, amount, purpose, and common risks before payment.' },
    category: '安全',
    provider: 'SafePay',
    price: { zh: '免费', en: 'Free' },
  },
  {
    id: 24,
    name: { zh: '家人远程协助', en: 'Family Remote Assist' },
    description: { zh: '在本人发起并授权后，让可信家人看见当前步骤并协助。', en: 'Lets a trusted relative help with the current step after explicit consent.' },
    category: '家庭',
    provider: 'Kindred AI',
    price: { zh: '¥12 / 月', en: '¥12 / mo' },
    featured: true,
  },
  {
    id: 25,
    name: { zh: '家庭相册整理', en: 'Family Album Organizer' },
    description: { zh: '按人物、时间和事件整理照片，并邀请家人补充说明。', en: 'Organizes photos by people and events, with family-added context.' },
    category: '家庭',
    provider: 'Memora',
    price: { zh: '¥18 / 月', en: '¥18 / mo' },
  },
  {
    id: 26,
    name: { zh: '视频通话字幕', en: 'Call Captions' },
    description: { zh: '为视频通话提供更大、更清楚的实时字幕与重点回顾。', en: 'Adds larger live captions and a clear recap to video calls.' },
    category: '家庭',
    provider: 'ClearTalk',
    price: { zh: '免费', en: 'Free' },
  },
  {
    id: 27,
    name: { zh: '复诊事项追踪', en: 'Follow-up Tracker' },
    description: { zh: '整理医生交代、待完成检查与下一次复诊准备。', en: 'Tracks instructions, tests, and preparation for the next appointment.' },
    category: '健康',
    provider: 'CareNote',
    price: { zh: '¥8 / 月', en: '¥8 / mo' },
  },
  {
    id: 28,
    name: { zh: '检查报告提问清单', en: 'Report Question List' },
    description: { zh: '不替代诊断，只把报告中的术语整理成可以询问医生的问题。', en: 'Does not diagnose; turns report terms into questions for a clinician.' },
    category: '健康',
    provider: 'CareNote',
    price: { zh: '¥6 / 次', en: '¥6 / use' },
  },
  {
    id: 29,
    name: { zh: '健康数据汇总', en: 'Health Data Summary' },
    description: { zh: '汇总设备与手工记录，生成便于本人和专业人员查看的趋势。', en: 'Combines device and manual records into a clear trend summary.' },
    category: '健康',
    provider: 'HealthBridge',
    price: { zh: '¥12 / 月', en: '¥12 / mo' },
  },
  {
    id: 30,
    name: { zh: '轻松学手机', en: 'Phone Learning Guide' },
    description: { zh: '根据当前屏幕即时讲解，不需要离开任务再看教程。', en: 'Explains the current screen without sending the user to a separate tutorial.' },
    category: '学习',
    provider: 'Deerlight Learn',
    price: { zh: '免费', en: 'Free' },
    featured: true,
  },
  {
    id: 31,
    name: { zh: '新闻看明白', en: 'Plain-language News' },
    description: { zh: '把长文章整理为事实、观点、来源和需要继续核实的内容。', en: 'Separates facts, viewpoints, sources, and claims needing verification.' },
    category: '学习',
    provider: 'Plainly',
    price: { zh: '免费', en: 'Free' },
  },
  {
    id: 32,
    name: { zh: '摄影兴趣课', en: 'Photography Club' },
    description: { zh: '围绕手机摄影安排短练习、作品反馈与同好交流。', en: 'Offers short phone-photo exercises, feedback, and peer exchange.' },
    category: '学习',
    provider: 'Lens Club',
    price: { zh: '¥12 / 月', en: '¥12 / mo' },
  },
  {
    id: 33,
    name: { zh: '社区活动发现', en: 'Nearby Activities' },
    description: { zh: '按照距离、兴趣、时间与行动便利度筛选附近活动。', en: 'Finds nearby activities by distance, interest, time, and accessibility.' },
    category: '生活',
    provider: 'NearMe',
    price: { zh: '免费', en: 'Free' },
  },
  {
    id: 34,
    name: { zh: '办事材料清单', en: 'Civic Service Checklist' },
    description: { zh: '把公共服务流程整理成材料、地点、时间和办理步骤。', en: 'Turns public-service processes into documents, places, times, and steps.' },
    category: '生活',
    provider: 'CivicPath',
    price: { zh: '免费', en: 'Free' },
  },
  {
    id: 35,
    name: { zh: '打车陪伴', en: 'Ride Companion' },
    description: { zh: '从叫车到抵达持续展示车辆、司机、路线与求助入口。', en: 'Keeps vehicle, driver, route, arrival, and help visible throughout a ride.' },
    category: '生活',
    provider: 'Wayhome',
    price: { zh: '¥2 / 次', en: '¥2 / use' },
  },
  {
    id: 36,
    name: { zh: '餐厅菜单助手', en: 'Menu Helper' },
    description: { zh: '放大菜单、解释菜品，并根据明确偏好协助点单。', en: 'Enlarges and explains menus, then helps order from stated preferences.' },
    category: '生活',
    provider: 'Goodday Studio',
    price: { zh: '免费', en: 'Free' },
  },
  {
    id: 37,
    name: { zh: '服务预约助手', en: 'Service Booking Assistant' },
    description: { zh: '帮助机构用户完成预约、改期、提醒与到访确认。', en: 'Handles booking, rescheduling, reminders, and arrival confirmation.' },
    category: '机构',
    provider: 'CareOps',
    price: { zh: '机构订阅', en: 'Provider plan' },
  },
  {
    id: 38,
    name: { zh: '探访记录', en: 'Visit Notes' },
    description: { zh: '把一线人员口述整理为结构化记录与后续行动。', en: 'Turns frontline voice notes into structured records and follow-ups.' },
    category: '机构',
    provider: 'CareOps',
    price: { zh: '机构订阅', en: 'Provider plan' },
  },
  {
    id: 39,
    name: { zh: '风险事件上报', en: 'Incident Reporting' },
    description: { zh: '用统一模板记录事实、证据、处置与通知对象。', en: 'Captures facts, evidence, response, and notification owners consistently.' },
    category: '机构',
    provider: 'SafeCare',
    price: { zh: '机构订阅', en: 'Provider plan' },
  },
  {
    id: 40,
    name: { zh: '员工培训问答', en: 'Staff Learning Assistant' },
    description: { zh: '基于机构规范回答一线问题，并标明来源与升级路径。', en: 'Answers from provider policies with sources and escalation paths.' },
    category: '机构',
    provider: 'Harbor Living',
    price: { zh: '机构订阅', en: 'Provider plan' },
  },
  {
    id: 41,
    name: { zh: '家庭服务周报', en: 'Family Service Brief' },
    description: { zh: '在授权范围内汇总一周服务、活动与需要家人确认的事项。', en: 'Summarizes weekly services, activities, and items needing family review.' },
    category: '机构',
    provider: 'Common Room',
    price: { zh: '¥99 / 月', en: '¥99 / mo' },
  },
  {
    id: 42,
    name: { zh: '方言实时字幕', en: 'Dialect Live Captions' },
    description: { zh: '把熟悉的方言转成大字字幕，并保留原始语音。', en: 'Turns familiar dialect speech into large captions while keeping audio.' },
    category: '学习',
    provider: 'Home Voice',
    price: { zh: '¥10 / 月', en: '¥10 / mo' },
  },
]

export function tx(text: BilingualText, lang: Lang) {
  return text[lang]
}
